// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Debugger.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NothingButNeurons.Shared.Messages {

  /// <summary>Holder for reflection information generated from Debugger.proto</summary>
  public static partial class DebuggerReflection {

    #region Descriptor
    /// <summary>File descriptor for Debugger.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DebuggerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5EZWJ1Z2dlci5wcm90bxIIZGVidWdnZXIaDFByb3Rvcy5wcm90byK0AQoX",
            "RGVidWdVSVN1YlVwZGF0ZU1lc3NhZ2USKQoIU2V2ZXJpdHkYASABKA4yFy5k",
            "ZWJ1Z2dlci5EZWJ1Z1NldmVyaXR5Eg8KB0NvbnRleHQYAiABKAkSDwoHU3Vt",
            "bWFyeRgDIAEoCRIPCgdNZXNzYWdlGAQgASgJEhMKC1NlbmRlckNsYXNzGAUg",
            "ASgJEhIKClNlbmRlck5hbWUYBiABKAkSEgoKUGFyZW50TmFtZRgHIAEoCSJx",
            "ChZEZWJ1Z1VJSW5jbHVkZXNNZXNzYWdlEhkKEUluY2x1ZGVTZW5kZXJJbmZv",
            "GAEgASgIEhkKEUluY2x1ZGVQYXJlbnRJbmZvGAIgASgIEiEKGUluY2x1ZGVT",
            "ZXJ2ZXJSZWNlaXZlZFRpbWUYAyABKAgiEwoRRGVidWdGbHVzaE1lc3NhZ2Ui",
            "FgoURGVidWdGbHVzaEFsbE1lc3NhZ2Ui/gEKFERlYnVnT3V0Ym91bmRNZXNz",
            "YWdlEikKCFNldmVyaXR5GAEgASgOMhcuZGVidWdnZXIuRGVidWdTZXZlcml0",
            "eRIPCgdDb250ZXh0GAIgASgJEg8KB1N1bW1hcnkYAyABKAkSDwoHTWVzc2Fn",
            "ZRgEIAEoCRITCgtTZW5kZXJDbGFzcxgFIAEoCRISCgpTZW5kZXJOYW1lGAYg",
            "ASgJEhgKEFNlbmRlclN5c3RlbUFkZHIYByABKAkSEgoKUGFyZW50TmFtZRgI",
            "IAEoCRIYChBQYXJlbnRTeXN0ZW1BZGRyGAkgASgJEhcKD01lc3NhZ2VTZW50",
            "VGltZRgKIAEoAyKZAgoTRGVidWdJbmJvdW5kTWVzc2FnZRIpCghTZXZlcml0",
            "eRgBIAEoDjIXLmRlYnVnZ2VyLkRlYnVnU2V2ZXJpdHkSDwoHQ29udGV4dBgC",
            "IAEoCRIPCgdTdW1tYXJ5GAMgASgJEg8KB01lc3NhZ2UYBCABKAkSEwoLU2Vu",
            "ZGVyQ2xhc3MYBSABKAkSEgoKU2VuZGVyTmFtZRgGIAEoCRIYChBTZW5kZXJT",
            "eXN0ZW1BZGRyGAcgASgJEhIKClBhcmVudE5hbWUYCCABKAkSGAoQUGFyZW50",
            "U3lzdGVtQWRkchgJIAEoCRIXCg9NZXNzYWdlU2VudFRpbWUYCiABKAMSGgoS",
            "U2VydmVyUmVjZWl2ZWRUaW1lGAsgASgDInMKFURlYnVnU3Vic2NyaWJlTWVz",
            "c2FnZRIeCgpTdWJzY3JpYmVyGAEgASgLMgouYWN0b3IuUElEEikKCFNldmVy",
            "aXR5GAIgASgOMhcuZGVidWdnZXIuRGVidWdTZXZlcml0eRIPCgdDb250ZXh0",
            "GAMgASgJIjkKF0RlYnVnVW5zdWJzY3JpYmVNZXNzYWdlEh4KClN1YnNjcmli",
            "ZXIYASABKAsyCi5hY3Rvci5QSUQqagoNRGVidWdTZXZlcml0eRIJCgVUcmFj",
            "ZRAAEggKBEluZm8QARIJCgVEZWJ1ZxACEgsKB1dhcm5pbmcQAxIJCgVBbGVy",
            "dBAEEgkKBUVycm9yEAUSDAoIQ3JpdGljYWwQBhIICgRUZXN0EAdCJKoCIU5v",
            "dGhpbmdCdXROZXVyb25zLlNoYXJlZC5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ProtosReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NothingButNeurons.Shared.Messages.DebugSeverity), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugUISubUpdateMessage), global::NothingButNeurons.Shared.Messages.DebugUISubUpdateMessage.Parser, new[]{ "Severity", "Context", "Summary", "Message", "SenderClass", "SenderName", "ParentName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugUIIncludesMessage), global::NothingButNeurons.Shared.Messages.DebugUIIncludesMessage.Parser, new[]{ "IncludeSenderInfo", "IncludeParentInfo", "IncludeServerReceivedTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugFlushMessage), global::NothingButNeurons.Shared.Messages.DebugFlushMessage.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugFlushAllMessage), global::NothingButNeurons.Shared.Messages.DebugFlushAllMessage.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugOutboundMessage), global::NothingButNeurons.Shared.Messages.DebugOutboundMessage.Parser, new[]{ "Severity", "Context", "Summary", "Message", "SenderClass", "SenderName", "SenderSystemAddr", "ParentName", "ParentSystemAddr", "MessageSentTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugInboundMessage), global::NothingButNeurons.Shared.Messages.DebugInboundMessage.Parser, new[]{ "Severity", "Context", "Summary", "Message", "SenderClass", "SenderName", "SenderSystemAddr", "ParentName", "ParentSystemAddr", "MessageSentTime", "ServerReceivedTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugSubscribeMessage), global::NothingButNeurons.Shared.Messages.DebugSubscribeMessage.Parser, new[]{ "Subscriber", "Severity", "Context" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NothingButNeurons.Shared.Messages.DebugUnsubscribeMessage), global::NothingButNeurons.Shared.Messages.DebugUnsubscribeMessage.Parser, new[]{ "Subscriber" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DebugSeverity {
    [pbr::OriginalName("Trace")] Trace = 0,
    [pbr::OriginalName("Info")] Info = 1,
    [pbr::OriginalName("Debug")] Debug = 2,
    [pbr::OriginalName("Warning")] Warning = 3,
    [pbr::OriginalName("Alert")] Alert = 4,
    [pbr::OriginalName("Error")] Error = 5,
    [pbr::OriginalName("Critical")] Critical = 6,
    [pbr::OriginalName("Test")] Test = 7,
  }

  #endregion

  #region Messages
  public sealed partial class DebugUISubUpdateMessage : pb::IMessage<DebugUISubUpdateMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugUISubUpdateMessage> _parser = new pb::MessageParser<DebugUISubUpdateMessage>(() => new DebugUISubUpdateMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugUISubUpdateMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUISubUpdateMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUISubUpdateMessage(DebugUISubUpdateMessage other) : this() {
      severity_ = other.severity_;
      context_ = other.context_;
      summary_ = other.summary_;
      message_ = other.message_;
      senderClass_ = other.senderClass_;
      senderName_ = other.senderName_;
      parentName_ = other.parentName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUISubUpdateMessage Clone() {
      return new DebugUISubUpdateMessage(this);
    }

    /// <summary>Field number for the "Severity" field.</summary>
    public const int SeverityFieldNumber = 1;
    private global::NothingButNeurons.Shared.Messages.DebugSeverity severity_ = global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NothingButNeurons.Shared.Messages.DebugSeverity Severity {
      get { return severity_; }
      set {
        severity_ = value;
      }
    }

    /// <summary>Field number for the "Context" field.</summary>
    public const int ContextFieldNumber = 2;
    private string context_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Context {
      get { return context_; }
      set {
        context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Summary" field.</summary>
    public const int SummaryFieldNumber = 3;
    private string summary_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Summary {
      get { return summary_; }
      set {
        summary_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderClass" field.</summary>
    public const int SenderClassFieldNumber = 5;
    private string senderClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderClass {
      get { return senderClass_; }
      set {
        senderClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderName" field.</summary>
    public const int SenderNameFieldNumber = 6;
    private string senderName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderName {
      get { return senderName_; }
      set {
        senderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ParentName" field.</summary>
    public const int ParentNameFieldNumber = 7;
    private string parentName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParentName {
      get { return parentName_; }
      set {
        parentName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugUISubUpdateMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugUISubUpdateMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Severity != other.Severity) return false;
      if (Context != other.Context) return false;
      if (Summary != other.Summary) return false;
      if (Message != other.Message) return false;
      if (SenderClass != other.SenderClass) return false;
      if (SenderName != other.SenderName) return false;
      if (ParentName != other.ParentName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) hash ^= Severity.GetHashCode();
      if (Context.Length != 0) hash ^= Context.GetHashCode();
      if (Summary.Length != 0) hash ^= Summary.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (SenderClass.Length != 0) hash ^= SenderClass.GetHashCode();
      if (SenderName.Length != 0) hash ^= SenderName.GetHashCode();
      if (ParentName.Length != 0) hash ^= ParentName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Context);
      }
      if (Summary.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Summary);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (SenderClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SenderClass);
      }
      if (SenderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderName);
      }
      if (ParentName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ParentName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Context);
      }
      if (Summary.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Summary);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (SenderClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SenderClass);
      }
      if (SenderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderName);
      }
      if (ParentName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ParentName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Severity);
      }
      if (Context.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
      }
      if (Summary.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Summary);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (SenderClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderClass);
      }
      if (SenderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderName);
      }
      if (ParentName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugUISubUpdateMessage other) {
      if (other == null) {
        return;
      }
      if (other.Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        Severity = other.Severity;
      }
      if (other.Context.Length != 0) {
        Context = other.Context;
      }
      if (other.Summary.Length != 0) {
        Summary = other.Summary;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.SenderClass.Length != 0) {
        SenderClass = other.SenderClass;
      }
      if (other.SenderName.Length != 0) {
        SenderName = other.SenderName;
      }
      if (other.ParentName.Length != 0) {
        ParentName = other.ParentName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 18: {
            Context = input.ReadString();
            break;
          }
          case 26: {
            Summary = input.ReadString();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 42: {
            SenderClass = input.ReadString();
            break;
          }
          case 50: {
            SenderName = input.ReadString();
            break;
          }
          case 58: {
            ParentName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 18: {
            Context = input.ReadString();
            break;
          }
          case 26: {
            Summary = input.ReadString();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 42: {
            SenderClass = input.ReadString();
            break;
          }
          case 50: {
            SenderName = input.ReadString();
            break;
          }
          case 58: {
            ParentName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DebugUIIncludesMessage : pb::IMessage<DebugUIIncludesMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugUIIncludesMessage> _parser = new pb::MessageParser<DebugUIIncludesMessage>(() => new DebugUIIncludesMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugUIIncludesMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUIIncludesMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUIIncludesMessage(DebugUIIncludesMessage other) : this() {
      includeSenderInfo_ = other.includeSenderInfo_;
      includeParentInfo_ = other.includeParentInfo_;
      includeServerReceivedTime_ = other.includeServerReceivedTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUIIncludesMessage Clone() {
      return new DebugUIIncludesMessage(this);
    }

    /// <summary>Field number for the "IncludeSenderInfo" field.</summary>
    public const int IncludeSenderInfoFieldNumber = 1;
    private bool includeSenderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeSenderInfo {
      get { return includeSenderInfo_; }
      set {
        includeSenderInfo_ = value;
      }
    }

    /// <summary>Field number for the "IncludeParentInfo" field.</summary>
    public const int IncludeParentInfoFieldNumber = 2;
    private bool includeParentInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeParentInfo {
      get { return includeParentInfo_; }
      set {
        includeParentInfo_ = value;
      }
    }

    /// <summary>Field number for the "IncludeServerReceivedTime" field.</summary>
    public const int IncludeServerReceivedTimeFieldNumber = 3;
    private bool includeServerReceivedTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeServerReceivedTime {
      get { return includeServerReceivedTime_; }
      set {
        includeServerReceivedTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugUIIncludesMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugUIIncludesMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IncludeSenderInfo != other.IncludeSenderInfo) return false;
      if (IncludeParentInfo != other.IncludeParentInfo) return false;
      if (IncludeServerReceivedTime != other.IncludeServerReceivedTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IncludeSenderInfo != false) hash ^= IncludeSenderInfo.GetHashCode();
      if (IncludeParentInfo != false) hash ^= IncludeParentInfo.GetHashCode();
      if (IncludeServerReceivedTime != false) hash ^= IncludeServerReceivedTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IncludeSenderInfo != false) {
        output.WriteRawTag(8);
        output.WriteBool(IncludeSenderInfo);
      }
      if (IncludeParentInfo != false) {
        output.WriteRawTag(16);
        output.WriteBool(IncludeParentInfo);
      }
      if (IncludeServerReceivedTime != false) {
        output.WriteRawTag(24);
        output.WriteBool(IncludeServerReceivedTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IncludeSenderInfo != false) {
        output.WriteRawTag(8);
        output.WriteBool(IncludeSenderInfo);
      }
      if (IncludeParentInfo != false) {
        output.WriteRawTag(16);
        output.WriteBool(IncludeParentInfo);
      }
      if (IncludeServerReceivedTime != false) {
        output.WriteRawTag(24);
        output.WriteBool(IncludeServerReceivedTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IncludeSenderInfo != false) {
        size += 1 + 1;
      }
      if (IncludeParentInfo != false) {
        size += 1 + 1;
      }
      if (IncludeServerReceivedTime != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugUIIncludesMessage other) {
      if (other == null) {
        return;
      }
      if (other.IncludeSenderInfo != false) {
        IncludeSenderInfo = other.IncludeSenderInfo;
      }
      if (other.IncludeParentInfo != false) {
        IncludeParentInfo = other.IncludeParentInfo;
      }
      if (other.IncludeServerReceivedTime != false) {
        IncludeServerReceivedTime = other.IncludeServerReceivedTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IncludeSenderInfo = input.ReadBool();
            break;
          }
          case 16: {
            IncludeParentInfo = input.ReadBool();
            break;
          }
          case 24: {
            IncludeServerReceivedTime = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IncludeSenderInfo = input.ReadBool();
            break;
          }
          case 16: {
            IncludeParentInfo = input.ReadBool();
            break;
          }
          case 24: {
            IncludeServerReceivedTime = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DebugFlushMessage : pb::IMessage<DebugFlushMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugFlushMessage> _parser = new pb::MessageParser<DebugFlushMessage>(() => new DebugFlushMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugFlushMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugFlushMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugFlushMessage(DebugFlushMessage other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugFlushMessage Clone() {
      return new DebugFlushMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugFlushMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugFlushMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugFlushMessage other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class DebugFlushAllMessage : pb::IMessage<DebugFlushAllMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugFlushAllMessage> _parser = new pb::MessageParser<DebugFlushAllMessage>(() => new DebugFlushAllMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugFlushAllMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugFlushAllMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugFlushAllMessage(DebugFlushAllMessage other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugFlushAllMessage Clone() {
      return new DebugFlushAllMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugFlushAllMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugFlushAllMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugFlushAllMessage other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class DebugOutboundMessage : pb::IMessage<DebugOutboundMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugOutboundMessage> _parser = new pb::MessageParser<DebugOutboundMessage>(() => new DebugOutboundMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugOutboundMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugOutboundMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugOutboundMessage(DebugOutboundMessage other) : this() {
      severity_ = other.severity_;
      context_ = other.context_;
      summary_ = other.summary_;
      message_ = other.message_;
      senderClass_ = other.senderClass_;
      senderName_ = other.senderName_;
      senderSystemAddr_ = other.senderSystemAddr_;
      parentName_ = other.parentName_;
      parentSystemAddr_ = other.parentSystemAddr_;
      messageSentTime_ = other.messageSentTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugOutboundMessage Clone() {
      return new DebugOutboundMessage(this);
    }

    /// <summary>Field number for the "Severity" field.</summary>
    public const int SeverityFieldNumber = 1;
    private global::NothingButNeurons.Shared.Messages.DebugSeverity severity_ = global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NothingButNeurons.Shared.Messages.DebugSeverity Severity {
      get { return severity_; }
      set {
        severity_ = value;
      }
    }

    /// <summary>Field number for the "Context" field.</summary>
    public const int ContextFieldNumber = 2;
    private string context_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Context {
      get { return context_; }
      set {
        context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Summary" field.</summary>
    public const int SummaryFieldNumber = 3;
    private string summary_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Summary {
      get { return summary_; }
      set {
        summary_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderClass" field.</summary>
    public const int SenderClassFieldNumber = 5;
    private string senderClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderClass {
      get { return senderClass_; }
      set {
        senderClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderName" field.</summary>
    public const int SenderNameFieldNumber = 6;
    private string senderName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderName {
      get { return senderName_; }
      set {
        senderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderSystemAddr" field.</summary>
    public const int SenderSystemAddrFieldNumber = 7;
    private string senderSystemAddr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderSystemAddr {
      get { return senderSystemAddr_; }
      set {
        senderSystemAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ParentName" field.</summary>
    public const int ParentNameFieldNumber = 8;
    private string parentName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParentName {
      get { return parentName_; }
      set {
        parentName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ParentSystemAddr" field.</summary>
    public const int ParentSystemAddrFieldNumber = 9;
    private string parentSystemAddr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParentSystemAddr {
      get { return parentSystemAddr_; }
      set {
        parentSystemAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MessageSentTime" field.</summary>
    public const int MessageSentTimeFieldNumber = 10;
    private long messageSentTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MessageSentTime {
      get { return messageSentTime_; }
      set {
        messageSentTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugOutboundMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugOutboundMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Severity != other.Severity) return false;
      if (Context != other.Context) return false;
      if (Summary != other.Summary) return false;
      if (Message != other.Message) return false;
      if (SenderClass != other.SenderClass) return false;
      if (SenderName != other.SenderName) return false;
      if (SenderSystemAddr != other.SenderSystemAddr) return false;
      if (ParentName != other.ParentName) return false;
      if (ParentSystemAddr != other.ParentSystemAddr) return false;
      if (MessageSentTime != other.MessageSentTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) hash ^= Severity.GetHashCode();
      if (Context.Length != 0) hash ^= Context.GetHashCode();
      if (Summary.Length != 0) hash ^= Summary.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (SenderClass.Length != 0) hash ^= SenderClass.GetHashCode();
      if (SenderName.Length != 0) hash ^= SenderName.GetHashCode();
      if (SenderSystemAddr.Length != 0) hash ^= SenderSystemAddr.GetHashCode();
      if (ParentName.Length != 0) hash ^= ParentName.GetHashCode();
      if (ParentSystemAddr.Length != 0) hash ^= ParentSystemAddr.GetHashCode();
      if (MessageSentTime != 0L) hash ^= MessageSentTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Context);
      }
      if (Summary.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Summary);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (SenderClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SenderClass);
      }
      if (SenderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderName);
      }
      if (SenderSystemAddr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SenderSystemAddr);
      }
      if (ParentName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ParentName);
      }
      if (ParentSystemAddr.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ParentSystemAddr);
      }
      if (MessageSentTime != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(MessageSentTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Context);
      }
      if (Summary.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Summary);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (SenderClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SenderClass);
      }
      if (SenderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderName);
      }
      if (SenderSystemAddr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SenderSystemAddr);
      }
      if (ParentName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ParentName);
      }
      if (ParentSystemAddr.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ParentSystemAddr);
      }
      if (MessageSentTime != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(MessageSentTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Severity);
      }
      if (Context.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
      }
      if (Summary.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Summary);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (SenderClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderClass);
      }
      if (SenderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderName);
      }
      if (SenderSystemAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderSystemAddr);
      }
      if (ParentName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentName);
      }
      if (ParentSystemAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentSystemAddr);
      }
      if (MessageSentTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MessageSentTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugOutboundMessage other) {
      if (other == null) {
        return;
      }
      if (other.Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        Severity = other.Severity;
      }
      if (other.Context.Length != 0) {
        Context = other.Context;
      }
      if (other.Summary.Length != 0) {
        Summary = other.Summary;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.SenderClass.Length != 0) {
        SenderClass = other.SenderClass;
      }
      if (other.SenderName.Length != 0) {
        SenderName = other.SenderName;
      }
      if (other.SenderSystemAddr.Length != 0) {
        SenderSystemAddr = other.SenderSystemAddr;
      }
      if (other.ParentName.Length != 0) {
        ParentName = other.ParentName;
      }
      if (other.ParentSystemAddr.Length != 0) {
        ParentSystemAddr = other.ParentSystemAddr;
      }
      if (other.MessageSentTime != 0L) {
        MessageSentTime = other.MessageSentTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 18: {
            Context = input.ReadString();
            break;
          }
          case 26: {
            Summary = input.ReadString();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 42: {
            SenderClass = input.ReadString();
            break;
          }
          case 50: {
            SenderName = input.ReadString();
            break;
          }
          case 58: {
            SenderSystemAddr = input.ReadString();
            break;
          }
          case 66: {
            ParentName = input.ReadString();
            break;
          }
          case 74: {
            ParentSystemAddr = input.ReadString();
            break;
          }
          case 80: {
            MessageSentTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 18: {
            Context = input.ReadString();
            break;
          }
          case 26: {
            Summary = input.ReadString();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 42: {
            SenderClass = input.ReadString();
            break;
          }
          case 50: {
            SenderName = input.ReadString();
            break;
          }
          case 58: {
            SenderSystemAddr = input.ReadString();
            break;
          }
          case 66: {
            ParentName = input.ReadString();
            break;
          }
          case 74: {
            ParentSystemAddr = input.ReadString();
            break;
          }
          case 80: {
            MessageSentTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DebugInboundMessage : pb::IMessage<DebugInboundMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugInboundMessage> _parser = new pb::MessageParser<DebugInboundMessage>(() => new DebugInboundMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugInboundMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugInboundMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugInboundMessage(DebugInboundMessage other) : this() {
      severity_ = other.severity_;
      context_ = other.context_;
      summary_ = other.summary_;
      message_ = other.message_;
      senderClass_ = other.senderClass_;
      senderName_ = other.senderName_;
      senderSystemAddr_ = other.senderSystemAddr_;
      parentName_ = other.parentName_;
      parentSystemAddr_ = other.parentSystemAddr_;
      messageSentTime_ = other.messageSentTime_;
      serverReceivedTime_ = other.serverReceivedTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugInboundMessage Clone() {
      return new DebugInboundMessage(this);
    }

    /// <summary>Field number for the "Severity" field.</summary>
    public const int SeverityFieldNumber = 1;
    private global::NothingButNeurons.Shared.Messages.DebugSeverity severity_ = global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NothingButNeurons.Shared.Messages.DebugSeverity Severity {
      get { return severity_; }
      set {
        severity_ = value;
      }
    }

    /// <summary>Field number for the "Context" field.</summary>
    public const int ContextFieldNumber = 2;
    private string context_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Context {
      get { return context_; }
      set {
        context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Summary" field.</summary>
    public const int SummaryFieldNumber = 3;
    private string summary_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Summary {
      get { return summary_; }
      set {
        summary_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderClass" field.</summary>
    public const int SenderClassFieldNumber = 5;
    private string senderClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderClass {
      get { return senderClass_; }
      set {
        senderClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderName" field.</summary>
    public const int SenderNameFieldNumber = 6;
    private string senderName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderName {
      get { return senderName_; }
      set {
        senderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SenderSystemAddr" field.</summary>
    public const int SenderSystemAddrFieldNumber = 7;
    private string senderSystemAddr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SenderSystemAddr {
      get { return senderSystemAddr_; }
      set {
        senderSystemAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ParentName" field.</summary>
    public const int ParentNameFieldNumber = 8;
    private string parentName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParentName {
      get { return parentName_; }
      set {
        parentName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ParentSystemAddr" field.</summary>
    public const int ParentSystemAddrFieldNumber = 9;
    private string parentSystemAddr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParentSystemAddr {
      get { return parentSystemAddr_; }
      set {
        parentSystemAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MessageSentTime" field.</summary>
    public const int MessageSentTimeFieldNumber = 10;
    private long messageSentTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MessageSentTime {
      get { return messageSentTime_; }
      set {
        messageSentTime_ = value;
      }
    }

    /// <summary>Field number for the "ServerReceivedTime" field.</summary>
    public const int ServerReceivedTimeFieldNumber = 11;
    private long serverReceivedTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ServerReceivedTime {
      get { return serverReceivedTime_; }
      set {
        serverReceivedTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugInboundMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugInboundMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Severity != other.Severity) return false;
      if (Context != other.Context) return false;
      if (Summary != other.Summary) return false;
      if (Message != other.Message) return false;
      if (SenderClass != other.SenderClass) return false;
      if (SenderName != other.SenderName) return false;
      if (SenderSystemAddr != other.SenderSystemAddr) return false;
      if (ParentName != other.ParentName) return false;
      if (ParentSystemAddr != other.ParentSystemAddr) return false;
      if (MessageSentTime != other.MessageSentTime) return false;
      if (ServerReceivedTime != other.ServerReceivedTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) hash ^= Severity.GetHashCode();
      if (Context.Length != 0) hash ^= Context.GetHashCode();
      if (Summary.Length != 0) hash ^= Summary.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (SenderClass.Length != 0) hash ^= SenderClass.GetHashCode();
      if (SenderName.Length != 0) hash ^= SenderName.GetHashCode();
      if (SenderSystemAddr.Length != 0) hash ^= SenderSystemAddr.GetHashCode();
      if (ParentName.Length != 0) hash ^= ParentName.GetHashCode();
      if (ParentSystemAddr.Length != 0) hash ^= ParentSystemAddr.GetHashCode();
      if (MessageSentTime != 0L) hash ^= MessageSentTime.GetHashCode();
      if (ServerReceivedTime != 0L) hash ^= ServerReceivedTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Context);
      }
      if (Summary.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Summary);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (SenderClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SenderClass);
      }
      if (SenderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderName);
      }
      if (SenderSystemAddr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SenderSystemAddr);
      }
      if (ParentName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ParentName);
      }
      if (ParentSystemAddr.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ParentSystemAddr);
      }
      if (MessageSentTime != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(MessageSentTime);
      }
      if (ServerReceivedTime != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(ServerReceivedTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Context);
      }
      if (Summary.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Summary);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
      if (SenderClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SenderClass);
      }
      if (SenderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SenderName);
      }
      if (SenderSystemAddr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SenderSystemAddr);
      }
      if (ParentName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ParentName);
      }
      if (ParentSystemAddr.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ParentSystemAddr);
      }
      if (MessageSentTime != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(MessageSentTime);
      }
      if (ServerReceivedTime != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(ServerReceivedTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Severity);
      }
      if (Context.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
      }
      if (Summary.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Summary);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (SenderClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderClass);
      }
      if (SenderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderName);
      }
      if (SenderSystemAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderSystemAddr);
      }
      if (ParentName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentName);
      }
      if (ParentSystemAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentSystemAddr);
      }
      if (MessageSentTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MessageSentTime);
      }
      if (ServerReceivedTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerReceivedTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugInboundMessage other) {
      if (other == null) {
        return;
      }
      if (other.Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        Severity = other.Severity;
      }
      if (other.Context.Length != 0) {
        Context = other.Context;
      }
      if (other.Summary.Length != 0) {
        Summary = other.Summary;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.SenderClass.Length != 0) {
        SenderClass = other.SenderClass;
      }
      if (other.SenderName.Length != 0) {
        SenderName = other.SenderName;
      }
      if (other.SenderSystemAddr.Length != 0) {
        SenderSystemAddr = other.SenderSystemAddr;
      }
      if (other.ParentName.Length != 0) {
        ParentName = other.ParentName;
      }
      if (other.ParentSystemAddr.Length != 0) {
        ParentSystemAddr = other.ParentSystemAddr;
      }
      if (other.MessageSentTime != 0L) {
        MessageSentTime = other.MessageSentTime;
      }
      if (other.ServerReceivedTime != 0L) {
        ServerReceivedTime = other.ServerReceivedTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 18: {
            Context = input.ReadString();
            break;
          }
          case 26: {
            Summary = input.ReadString();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 42: {
            SenderClass = input.ReadString();
            break;
          }
          case 50: {
            SenderName = input.ReadString();
            break;
          }
          case 58: {
            SenderSystemAddr = input.ReadString();
            break;
          }
          case 66: {
            ParentName = input.ReadString();
            break;
          }
          case 74: {
            ParentSystemAddr = input.ReadString();
            break;
          }
          case 80: {
            MessageSentTime = input.ReadInt64();
            break;
          }
          case 88: {
            ServerReceivedTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 18: {
            Context = input.ReadString();
            break;
          }
          case 26: {
            Summary = input.ReadString();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
          case 42: {
            SenderClass = input.ReadString();
            break;
          }
          case 50: {
            SenderName = input.ReadString();
            break;
          }
          case 58: {
            SenderSystemAddr = input.ReadString();
            break;
          }
          case 66: {
            ParentName = input.ReadString();
            break;
          }
          case 74: {
            ParentSystemAddr = input.ReadString();
            break;
          }
          case 80: {
            MessageSentTime = input.ReadInt64();
            break;
          }
          case 88: {
            ServerReceivedTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DebugSubscribeMessage : pb::IMessage<DebugSubscribeMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugSubscribeMessage> _parser = new pb::MessageParser<DebugSubscribeMessage>(() => new DebugSubscribeMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugSubscribeMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugSubscribeMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugSubscribeMessage(DebugSubscribeMessage other) : this() {
      subscriber_ = other.subscriber_ != null ? other.subscriber_.Clone() : null;
      severity_ = other.severity_;
      context_ = other.context_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugSubscribeMessage Clone() {
      return new DebugSubscribeMessage(this);
    }

    /// <summary>Field number for the "Subscriber" field.</summary>
    public const int SubscriberFieldNumber = 1;
    private global::Proto.PID subscriber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.PID Subscriber {
      get { return subscriber_; }
      set {
        subscriber_ = value;
      }
    }

    /// <summary>Field number for the "Severity" field.</summary>
    public const int SeverityFieldNumber = 2;
    private global::NothingButNeurons.Shared.Messages.DebugSeverity severity_ = global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NothingButNeurons.Shared.Messages.DebugSeverity Severity {
      get { return severity_; }
      set {
        severity_ = value;
      }
    }

    /// <summary>Field number for the "Context" field.</summary>
    public const int ContextFieldNumber = 3;
    private string context_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Context {
      get { return context_; }
      set {
        context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugSubscribeMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugSubscribeMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Subscriber, other.Subscriber)) return false;
      if (Severity != other.Severity) return false;
      if (Context != other.Context) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (subscriber_ != null) hash ^= Subscriber.GetHashCode();
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) hash ^= Severity.GetHashCode();
      if (Context.Length != 0) hash ^= Context.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (subscriber_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Subscriber);
      }
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Context);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (subscriber_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Subscriber);
      }
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Severity);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Context);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (subscriber_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Subscriber);
      }
      if (Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Severity);
      }
      if (Context.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugSubscribeMessage other) {
      if (other == null) {
        return;
      }
      if (other.subscriber_ != null) {
        if (subscriber_ == null) {
          Subscriber = new global::Proto.PID();
        }
        Subscriber.MergeFrom(other.Subscriber);
      }
      if (other.Severity != global::NothingButNeurons.Shared.Messages.DebugSeverity.Trace) {
        Severity = other.Severity;
      }
      if (other.Context.Length != 0) {
        Context = other.Context;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (subscriber_ == null) {
              Subscriber = new global::Proto.PID();
            }
            input.ReadMessage(Subscriber);
            break;
          }
          case 16: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 26: {
            Context = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (subscriber_ == null) {
              Subscriber = new global::Proto.PID();
            }
            input.ReadMessage(Subscriber);
            break;
          }
          case 16: {
            Severity = (global::NothingButNeurons.Shared.Messages.DebugSeverity) input.ReadEnum();
            break;
          }
          case 26: {
            Context = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DebugUnsubscribeMessage : pb::IMessage<DebugUnsubscribeMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DebugUnsubscribeMessage> _parser = new pb::MessageParser<DebugUnsubscribeMessage>(() => new DebugUnsubscribeMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DebugUnsubscribeMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NothingButNeurons.Shared.Messages.DebuggerReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUnsubscribeMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUnsubscribeMessage(DebugUnsubscribeMessage other) : this() {
      subscriber_ = other.subscriber_ != null ? other.subscriber_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DebugUnsubscribeMessage Clone() {
      return new DebugUnsubscribeMessage(this);
    }

    /// <summary>Field number for the "Subscriber" field.</summary>
    public const int SubscriberFieldNumber = 1;
    private global::Proto.PID subscriber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.PID Subscriber {
      get { return subscriber_; }
      set {
        subscriber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DebugUnsubscribeMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DebugUnsubscribeMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Subscriber, other.Subscriber)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (subscriber_ != null) hash ^= Subscriber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (subscriber_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Subscriber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (subscriber_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Subscriber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (subscriber_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Subscriber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DebugUnsubscribeMessage other) {
      if (other == null) {
        return;
      }
      if (other.subscriber_ != null) {
        if (subscriber_ == null) {
          Subscriber = new global::Proto.PID();
        }
        Subscriber.MergeFrom(other.Subscriber);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (subscriber_ == null) {
              Subscriber = new global::Proto.PID();
            }
            input.ReadMessage(Subscriber);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (subscriber_ == null) {
              Subscriber = new global::Proto.PID();
            }
            input.ReadMessage(Subscriber);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
